
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: mlynarczyk/io-lab-docker-ci-public:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    volumes:
      - redis-data:/data


volumes:
  redis-data: