
version: '3.0'
services:
  web:
    # TODO: build context, ports and redis dependency
    build: .
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 5000:6379
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc3
    # TODO: missing persistence for redis. You need to persist /data directory.
    volumes:
      - redis-data:/data


volumes:
  redis-data:

